### ISSUE TITLE
How is this licensed?

### ISSUE THREAD

**Issue by dmyersturnbull** [nst/UniBinary#5]
@nst This is fantastic, thanks for putting it up!  
It's niche, but I have a real need for it (in the NLP component of [this thing](https://github.com/dmyersturnbull/mandos)).

*How is it licensed?*

If I have your permission and a suitable license (e.g. Apache or MIT), I would love to adopt the Python package and publish it to PyPi.

**Comment by nst** [comment]
You can assume it's MIT license. I'll formally update the repo later.

**Comment by nst** [comment]
MIT https://github.com/nst/UniBinary/blob/master/LICENSE.txt
